services:
  mysql:
    container_name: mysql
    image: mysql:8.0.40
    ports:
      - "3307:3306"
    volumes:
       - "./sql-scripts:/docker-entrypoint-initdb.d"
    env_file: .env
    environment:
      - MYSQL_DATABASE=superleaguedb
      - MYSQL_ROOT_PASSWORD=${DB_USER_PASSWD}
      - MYSQL_USER=superleagueuser
      - MYSQL_PASSWORD=${DB_USER_PASSWD}
    networks:
      - stack
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p ${DB_USER_PASSWD}"]
      start_period: 600s

  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/superleaguedb?serverTimezone=UTC
    networks:
      - stack
    depends_on:
      mysql:
        condition: service_healthy

networks:
  stack:
    name: stack
    driver: bridge
